name: My Workflow File 
on:
  push:
    branches: [main]
    
jobs: 
  builds:
    runs-on: Ubuntu-16.04 
    name: My Build
    steps:
      - name: Check out code 
        uses: action/checkout@v2
      - name: Setup go
        uses: action/setup-go@3.5.8
        with:
          gp-version: 1.19.3
      - name: go installed
        run: |
          go version
      
