name: My Workflow File 
on:
  push:
    branches: [main]
    
jobs: 
  builds:
    name: My Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code 
        uses: actions/checkout@v2
        
      - name: Print and list out content
        run: echo Hello There!
        
      - name: Setup go
        uses: actions/setup-go@v3.5.0
        with:
          gp-version: 1.19.3
          
      - name: go installed
        run: |
          go version
          go test -v
          
          
      - name: Install dependencies for GO
        run: |
          go install gotest.tools/gotestsum@latest
          go test -v
          go test -v | gotestsum --junitfile report.xml
          ls 
          
      - if: ${{ failure()}}
        uses: dacbd/create-issue-action@main
        with:
          token: ${{ github.token }}
          title: Action workflow failed.
          body: |
            ### Context
            [Failed Run](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
            [Codebase](https://github.com/${{ github.repository }}/tree/${{ github.sha }})
            Workflow name - `${{ github.workflow }}`
            Job -           `${{ github.job }}`
            status -        `${{ job.status }}`
          assignees: Jedrek1996

      - name: Validate the Go Codes
        uses: goreleaser/goreleaser-action@v2.6.1
        with:
            args: check
            
      - name: Release the Go Codes
        uses: goreleaser/goreleaser-action@v2.6.1
        with:
          args: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
          
          
      - name: Send Push Notification
        uses: techulus/push-github-action@v0.0.2
        env:
          API_KEY: ${{ secrets.PUSH_API_KEY }}
          MESSAGE: "There is a new issue 😅"
          
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action/composite@v2
        if: always()
        with:
          junit_files: "report.xml"  
