name: My Workflow File 
on:
  push:
    branches: [main]
    
jobs: 
  builds:
    name: My Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code 
        uses: action/checkout@v2
        
      - name: Print and list out content
        run: echo Hello There!
        
      - name: Setup go
        uses: action/setup-go@3.5.0
        with:
          gp-version: 1.19.3
          
      - name: go installed
        run: |
          go version
          go test -v
      
